[tool.poetry]
name = "x"
version = "0.1.0"
description = ""
authors = ["Ben Madley <ben.madley@madetech.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^7.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
